import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Appwrapper } from "./Context";
import Message from "./_globalcomps/Message";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Appwrapper>
          <Message />
          {children}
        </Appwrapper>
      </body>
    </html>
  );
}
